### ISSUE TITLE
Error after upgrade to 3.0.5 : error TS1183: An implementation cannot be declared in ambient contexts.

### ISSUE THREAD

**Issue by nickykln** [NathanWalker/nativescript-fancyalert#62]
I used to have the version ^2.0.0. I have migrated to ^3.0.5 and know my project is not compiling anymore and I've got the TS compilation Error :
ERROR in node_modules/nativescript-fancyalert/index.d.ts(49,28): error TS1183: An implementation cannot be declared in ambient contexts.

**Comment by NathanWalker** [comment]
@nickykln what version of TypeScript and {N} you using? I don't see that error on this end. - I use 4.2+ with typescript 2.9+

**Comment by NathanWalker** [comment]
Fixed in latest.
